version: '3'
services:
  billtraq-db:
    image: postgres:14.2-alpine
    container_name: billtraq-postgres-14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: 
      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  billtraq-web:
    build: .
    command: "./bin/rails server"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - app-storage:/rails/storage
    depends_on:
      - billtraq-db
    ports:
      - "3000:3000"

  redis:
    image: redis:latest
    container_name: billtraq-redis
    ports:
      - "6379:6379"

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      - RAILS_ENV=${RAILS_ENV}
    volumes:
      - app-storage:/rails/storage
    depends_on:
      - billtraq-web
      - redis

volumes:
  postgres_data: {}
  app-storage: {}
